plugins {
    id 'application'
}

group = 'jogodavelha'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jline:jline:3.27.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

application {
    mainClass = 'jogodavelha2.Main'
    applicationDefaultJvmArgs = ['--enable-native-access=ALL-UNNAMED']
}